// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA6l-I7gyAIZZPO6LxBMe7nFE6Bm5139iY',
    appId: '1:1091435522886:web:3da46354d0a3736a315347',
    messagingSenderId: '1091435522886',
    projectId: 'infinite-tictactoe-abbe2',
    authDomain: 'infinite-tictactoe-abbe2.firebaseapp.com',
    storageBucket: 'infinite-tictactoe-abbe2.firebasestorage.app',
    measurementId: 'G-0PRZJPBL4L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAroXoIfwBcJ9FUpmfs2fssuxFdfWcxVwk',
    appId: '1:1091435522886:android:7208f851ab211fe8315347',
    messagingSenderId: '1091435522886',
    projectId: 'infinite-tictactoe-abbe2',
    storageBucket: 'infinite-tictactoe-abbe2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB1mz8q8cslo1g6Y5Od07atz96qQTp_42o',
    appId: '1:1091435522886:ios:2b9f5c37c9a98e30315347',
    messagingSenderId: '1091435522886',
    projectId: 'infinite-tictactoe-abbe2',
    storageBucket: 'infinite-tictactoe-abbe2.firebasestorage.app',
    iosBundleId: 'com.example.infiniteTictactoe',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB1mz8q8cslo1g6Y5Od07atz96qQTp_42o',
    appId: '1:1091435522886:ios:2b9f5c37c9a98e30315347',
    messagingSenderId: '1091435522886',
    projectId: 'infinite-tictactoe-abbe2',
    storageBucket: 'infinite-tictactoe-abbe2.firebasestorage.app',
    iosBundleId: 'com.example.infiniteTictactoe',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA6l-I7gyAIZZPO6LxBMe7nFE6Bm5139iY',
    appId: '1:1091435522886:web:3274f68deec5bbd0315347',
    messagingSenderId: '1091435522886',
    projectId: 'infinite-tictactoe-abbe2',
    authDomain: 'infinite-tictactoe-abbe2.firebaseapp.com',
    storageBucket: 'infinite-tictactoe-abbe2.firebasestorage.app',
    measurementId: 'G-964S9PFWPM',
  );
}
