import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:infinite_tictactoe/home_screen.dart';
import 'firebase_options.dart'; // generated by FlutterFire CLI

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp(options: DefaultFirebaseOptions.currentPlatform);
  runApp(const MaterialApp(home: HomeScreen()));
}